---
- name: Install sanoid dependencies
  package:
    name:
      - libconfig-inifiles-perl
      - libcapture-tiny-perl
      - libdate-calc-perl
      - pv
      - lzop
      - mbuffer
    state: present
  tags:
    - snapshots
    - sanoid
    - packages

- name: Download sanoid
  git:
    repo: https://github.com/jimsalterjrs/sanoid.git
    dest: /opt/sanoid
    version: master
    force: yes
  tags:
    - snapshots
    - sanoid
    - install

- name: Create sanoid symlinks
  file:
    src: "/opt/sanoid/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    force: yes
  loop:
    - sanoid
    - syncoid
    - findoid
  tags:
    - snapshots
    - sanoid
    - install

- name: Create sanoid configuration directory
  file:
    path: /etc/sanoid
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - snapshots
    - sanoid
    - config

- name: Generate sanoid configuration
  template:
    src: sanoid.conf.j2
    dest: /etc/sanoid/sanoid.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart sanoid timer
  tags:
    - snapshots
    - sanoid
    - config

- name: Create sanoid systemd service
  template:
    src: sanoid.service.j2
    dest: /etc/systemd/system/sanoid.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart sanoid timer
  tags:
    - snapshots
    - sanoid
    - systemd

- name: Create sanoid systemd timer
  template:
    src: sanoid.timer.j2
    dest: /etc/systemd/system/sanoid.timer
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload systemd
    - restart sanoid timer
  tags:
    - snapshots
    - sanoid
    - systemd

- name: Enable and start sanoid timer
  systemd:
    name: sanoid.timer
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - snapshots
    - sanoid
    - systemd