---
- name: Create service groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid }}"
    state: present
  loop: "{{ service_groups }}"
  tags:
    - users
    - groups

- name: Create service users
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    home: "{{ '/mnt/' + zfs_pool + ('/databases/' if item.category == 'Database' else '/apps/') + item.name }}"
    shell: /bin/false
    comment: "{{ item.description }}"
    create_home: false
    system: true
    state: present
  loop: "{{ service_users }}"
  tags:
    - users

- name: Configure supplementary group memberships - download access
  user:
    name: "{{ item }}"
    groups: download
    append: true
  loop: "{{ supplementary_groups.download_access }}"
  tags:
    - users
    - group_memberships

- name: Configure supplementary group memberships - media access
  user:
    name: "{{ item }}"
    groups: media
    append: true
  loop: "{{ supplementary_groups.media_access }}"
  tags:
    - users
    - group_memberships

- name: Configure supplementary group memberships - container access
  user:
    name: "{{ item }}"
    groups: containers
    append: true
  loop: "{{ supplementary_groups.container_access }}"
  tags:
    - users
    - group_memberships

- name: Configure supplementary group memberships - monitor access
  user:
    name: "{{ item }}"
    groups: monitor
    append: true
  loop: "{{ supplementary_groups.monitor_access }}"
  tags:
    - users
    - group_memberships

- name: Generate users and groups reference file
  template:
    src: users_groups_reference.txt.j2
    dest: /root/users_groups_reference.txt
    owner: root
    group: root
    mode: '0644'
  tags:
    - users
    - documentation