---
truenas_api_url: "http://{{ ansible_host }}"
truenas_api_key: "{{ api_key }}"

zfs_arc_settings:
  arc_max: 8589934592
  arc_min: 2147483648

cpu_governor_settings:
  governor: "performance"
  available_governors:
    - "performance"
    - "powersave"
    - "ondemand"
    - "conservative"

network_buffer_settings:
  net_core_rmem_max: 134217728
  net_core_wmem_max: 134217728
  net_core_rmem_default: 262144
  net_core_wmem_default: 262144
  net_ipv4_tcp_rmem: "4096 65536 134217728"
  net_ipv4_tcp_wmem: "4096 65536 134217728"
  net_core_netdev_max_backlog: 5000
  net_ipv4_tcp_congestion_control: "bbr"

storage_io_settings:
  scheduler: "mq-deadline"
  queue_depth: 32
  read_ahead_kb: 4096

performance_reporting:
  enabled: true
  report_path: "/tmp/performance_optimization_report.txt"