---
- name: Configure ZFS ARC Memory Settings
  include_tasks: zfs_arc_config.yml
  tags:
    - performance
    - zfs
    - memory

- name: Configure CPU Governor Settings
  include_tasks: cpu_governor_config.yml
  tags:
    - performance
    - cpu
    - governor

- name: Configure Network Buffer Optimizations
  include_tasks: network_buffer_config.yml
  tags:
    - performance
    - network
    - buffers

- name: Configure Storage I/O Scheduler
  include_tasks: storage_io_config.yml
  tags:
    - performance
    - storage
    - io

- name: Generate Performance Report
  include_tasks: performance_report.yml
  when: performance_reporting.enabled | default(true)
  tags:
    - performance
    - reporting