---
- name: Performance Tunables Configuration
  tags:
    - performance
    - tunables
  block:
    - name: Display performance configuration start
      debug:
        msg:
          - "Starting TrueNAS SCALE performance tunable configuration..."
          - "SYSCTL tunables: {{ performance_sysctl_tunables | length }} items"
          - "ZFS tunables: {{ performance_zfs_tunables | length }} items"
          - "UDEV script: {{ 'enabled' if performance_enable_udev else 'disabled' }}"
          - "Delete existing strategy: {{ 'enabled' if performance_delete_existing else 'disabled' }}"

    - name: Configure SYSCTL tunables
      include_tasks: sysctl_tunables.yml
      when: performance_enable_sysctl | default(true)
      tags:
        - sysctl

    - name: Configure ZFS module parameters
      include_tasks: zfs_tunables.yml
      when: performance_enable_zfs | default(true)
      tags:
        - zfs

    - name: Configure UDEV block device settings
      include_tasks: udev_tunables.yml
      when: performance_enable_udev | default(true)
      tags:
        - udev

    - name: Generate performance report
      include_tasks: report.yml
      tags:
        - report

  rescue:
    - name: Handle performance configuration errors
      debug:
        msg:
          - "Error occurred during performance configuration:"
          - "{{ ansible_failed_result.msg | default('Unknown error') }}"
          - "Check TrueNAS API connectivity and permissions"

    - name: Fail with detailed error
      fail:
        msg: "Performance tunable configuration failed. Check the error above and TrueNAS API access."