---
- name: Generate Performance Configuration Report
  tags:
    - report
    - performance
  block:
    - name: Create performance report template
      set_fact:
        performance_report_content: |
          # TrueNAS SCALE Performance Tunable Configuration Report
          Generated: {{ ansible_date_time.iso8601 }}
          Ansible Host: {{ ansible_host | default('localhost') }}

          ## Configuration Summary

          ### SYSCTL Tunables
          {% if performance_enable_sysctl %}
          ✅ **ENABLED** - {{ performance_sysctl_tunables | length }} tunables configured
          {% for tunable in performance_sysctl_tunables %}
          - `{{ tunable.var }}` = `{{ tunable.value }}`
            {{ tunable.comment | default('No description') }}
          {% endfor %}
          {% else %}
          ❌ **DISABLED** - SYSCTL tunables not configured
          {% endif %}

          ### ZFS Module Parameters
          {% if performance_enable_zfs %}
          ✅ **ENABLED** - {{ performance_zfs_tunables | length }} tunables configured
          {% for tunable in performance_zfs_tunables %}
          - `{{ tunable.var }}` = `{{ tunable.value }}`
            {{ tunable.comment | default('No description') }}
          {% endfor %}
          {% else %}
          ❌ **DISABLED** - ZFS tunables not configured
          {% endif %}

          ### Block Device Performance (UDEV)
          {% if performance_enable_udev %}
          ✅ **ENABLED** - {{ performance_udev_tunables | length }} UDEV rules configured via API

          **UDEV Rules Created:**
          {% for tunable in performance_udev_tunables %}
          - `{{ tunable.var }}.rules` - {{ tunable.comment | default('UDEV performance rule') }}
          {% endfor %}

          **Optimizations Applied:**
          - I/O scheduler selection (mq-deadline for HDDs, none for SSDs/NVMe)
          - Read-ahead optimization (1MB for most devices)
          - Queue depth settings (256 requests)
          - CPU affinity for I/O completion
          - Entropy collection disabled for performance
          - I/O merging enabled
          - Write-back throttling configured
          - NVMe polling enabled where supported
          - Network TX queue optimization for 10GbE
          {% else %}
          ❌ **DISABLED** - Block device optimization not configured
          {% endif %}

          ## Performance Expectations

          ### Memory Configuration (192GB System)
          - **ZFS ARC**: ~153GB (80% of RAM)
          - **Container Memory**: ~38GB available
          - **Swap Usage**: Minimized (swappiness=1)
          - **Dirty Memory**: Max 10% (~19GB) before forced writes

          ### Network Performance (10GbE)
          - **TCP Buffers**: 128MB max send/receive
          - **Congestion Control**: BBR for optimal 10GbE utilization
          - **Connection Scaling**: 8K max connections, expanded port range
          - **Packet Processing**: Optimized for high-bandwidth workloads

          ### Storage Performance
          - **I/O Scheduling**: Hardware-appropriate schedulers
          - **Prefetch**: 64MB distance for sequential workloads
          - **ARC Management**: Intelligent metadata and data caching
          - **Write Optimization**: 8GB dirty data threshold

          ## Recommended Next Steps

          1. **Reboot Required**: Many kernel and ZFS parameters require a system reboot
          2. **Monitor Performance**: Watch memory usage between containers and ZFS ARC
          3. **Validate Settings**: Use `sysctl -a | grep <parameter>` to verify sysctls
          4. **Check ZFS Parameters**: Use `cat /sys/module/zfs/parameters/<param>` to verify ZFS settings
          5. **Review UDEV Rules**: Check `/etc/udev/rules.d/` for performance rules after reboot
          6. **Review Block Devices**: Check `/sys/block/*/queue/` settings after reboot
          7. **Load Testing**: Perform baseline performance tests on containers and storage

          ## Verification Commands

          ```bash
          # Verify SYSCTL settings
          sysctl vm.swappiness vm.dirty_ratio net.core.rmem_max

          # Check ZFS ARC status
          cat /proc/spl/kstat/zfs/arcstats

          # Verify UDEV rules were created
          ls -la /etc/udev/rules.d/*block-performance*

          # Verify block device settings (after reboot)
          find /sys/block -name scheduler -exec grep -H . {} \;
          find /sys/block -name read_ahead_kb -exec grep -H . {} \;

          # Check network interface settings
          cat /sys/class/net/*/tx_queue_len

          # Monitor network performance
          ss -tuln | wc -l  # Active connections
          iftop  # Real-time network usage

          # Check container memory usage
          docker stats --no-stream
          ```

          ## Support Information

          - **Configuration Method**: TrueNAS SCALE API via Ansible
          - **Tunable Count**: {{ (performance_sysctl_tunables | length) + (performance_zfs_tunables | length) + (performance_udev_tunables | length) }} total parameters
          - **Target Workload**: 61 containerized services across 11 categories
          - **Hardware Profile**: 192GB RAM, 10GbE networking, ZFS storage

          ---
          *Report generated by Ansible performance role*
          *For questions or issues, refer to the role documentation*

    - name: Write performance report to temporary file
      copy:
        content: "{{ performance_report_content }}"
        dest: "/tmp/truenas_performance_configuration_report.md"
        mode: '0644'
      delegate_to: localhost

    - name: Display performance configuration summary
      debug:
        msg:
          - "Performance configuration completed successfully!"
          - ""
          - "📊 CONFIGURATION SUMMARY:"
          - "  • SYSCTL tunables: {{ performance_sysctl_tunables | length if performance_enable_sysctl else 'disabled' }}"
          - "  • ZFS parameters: {{ performance_zfs_tunables | length if performance_enable_zfs else 'disabled' }}"
          - "  • UDEV rules: {{ performance_udev_tunables | length if performance_enable_udev else 'disabled' }}"
          - ""
          - "📋 REPORT GENERATED:"
          - "  • Location: /tmp/truenas_performance_configuration_report.md"
          - "  • Contains: Detailed configuration, verification commands, next steps"
          - ""
          - "⚠️  IMPORTANT NEXT STEPS:"
          - "  1. REBOOT REQUIRED - Many settings need a system restart"
          - "  2. Review the generated report for verification commands"
          - "  3. Monitor memory usage between containers and ZFS ARC"
          - "  4. Perform baseline performance testing"
          - ""
          - "🔍 QUICK VERIFICATION (after reboot):"
          - "  • sysctl vm.swappiness"
          - "  • cat /sys/module/zfs/parameters/zfs_arc_max"
          - "  • cat /sys/block/sda/queue/scheduler"