---
- name: Get current ZFS ARC settings
  uri:
    url: "{{ truenas_api_url }}/api/v2.0/tunable"
    method: GET
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
    validate_certs: false
  register: current_tunables

- name: Set ZFS ARC maximum memory
  uri:
    url: "{{ truenas_api_url }}/api/v2.0/tunable"
    method: POST
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
      Content-Type: "application/json"
    body_format: json
    body:
      var: "vfs.zfs.arc_max"
      value: "{{ zfs_arc_settings.arc_max }}"
      type: "SYSCTL"
      comment: "ZFS ARC maximum memory limit - configured by Ansible"
      enabled: true
    validate_certs: false
    status_code: [200, 201]
  when: current_tunables.json | selectattr('var', 'equalto', 'vfs.zfs.arc_max') | list | length == 0
  register: arc_max_result

- name: Update existing ZFS ARC maximum memory
  uri:
    url: "{{ truenas_api_url }}/api/v2.0/tunable/{{ (current_tunables.json | selectattr('var', 'equalto', 'vfs.zfs.arc_max') | first).id }}"
    method: PUT
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
      Content-Type: "application/json"
    body_format: json
    body:
      var: "vfs.zfs.arc_max"
      value: "{{ zfs_arc_settings.arc_max }}"
      type: "SYSCTL"
      comment: "ZFS ARC maximum memory limit - configured by Ansible"
      enabled: true
    validate_certs: false
  when: current_tunables.json | selectattr('var', 'equalto', 'vfs.zfs.arc_max') | list | length > 0
  register: arc_max_update_result

- name: Set ZFS ARC minimum memory
  uri:
    url: "{{ truenas_api_url }}/api/v2.0/tunable"
    method: POST
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
      Content-Type: "application/json"
    body_format: json
    body:
      var: "vfs.zfs.arc_min"
      value: "{{ zfs_arc_settings.arc_min }}"
      type: "SYSCTL"
      comment: "ZFS ARC minimum memory limit - configured by Ansible"
      enabled: true
    validate_certs: false
    status_code: [200, 201]
  when: current_tunables.json | selectattr('var', 'equalto', 'vfs.zfs.arc_min') | list | length == 0
  register: arc_min_result

- name: Update existing ZFS ARC minimum memory
  uri:
    url: "{{ truenas_api_url }}/api/v2.0/tunable/{{ (current_tunables.json | selectattr('var', 'equalto', 'vfs.zfs.arc_min') | first).id }}"
    method: PUT
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
      Content-Type: "application/json"
    body_format: json
    body:
      var: "vfs.zfs.arc_min"
      value: "{{ zfs_arc_settings.arc_min }}"
      type: "SYSCTL"
      comment: "ZFS ARC minimum memory limit - configured by Ansible"
      enabled: true
    validate_certs: false
  when: current_tunables.json | selectattr('var', 'equalto', 'vfs.zfs.arc_min') | list | length > 0
  register: arc_min_update_result

- name: Display ZFS ARC configuration results
  debug:
    msg: |
      ZFS ARC Memory Configuration:
      - ARC Max: {{ zfs_arc_settings.arc_max | int / 1024 / 1024 / 1024 }}GB
      - ARC Min: {{ zfs_arc_settings.arc_min | int / 1024 / 1024 / 1024 }}GB
      - Configuration Status: {{ 'Updated' if arc_max_update_result.changed or arc_min_update_result.changed else 'Created' if arc_max_result.changed or arc_min_result.changed else 'Already Configured' }}