---
- name: ZFS Module Performance Parameters
  tags:
    - zfs
    - performance
  block:
    - name: Get existing ZFS tunables
      uri:
        url: "{{ truenas_api_url }}/tunable"
        method: GET
        headers:
          Authorization: "Bearer {{ truenas_api_key }}"
        status_code: [200]
        validate_certs: "{{ truenas_validate_certs }}"
      register: existing_tunables
      check_mode: false

    - name: Filter existing ZFS tunables for performance variables
      set_fact:
        existing_zfs_performance_tunables: >-
          {{
            existing_tunables.json |
            selectattr('type', 'equalto', 'ZFS') |
            selectattr('var', 'in', performance_zfs_tunables | map(attribute='var') | list) |
            list
          }}

    - name: Delete existing performance ZFS tunables
      uri:
        url: "{{ truenas_api_url }}/tunable/{{ item.id }}"
        method: DELETE
        headers:
          Authorization: "Bearer {{ truenas_api_key }}"
        status_code: [200]
        validate_certs: "{{ truenas_validate_certs }}"
      loop: "{{ existing_zfs_performance_tunables }}"
      when:
        - performance_delete_existing | default(true)
        - existing_zfs_performance_tunables | length > 0
      loop_control:
        label: "{{ item.var }} (ID: {{ item.id }})"

    - name: Create/update ZFS performance tunables
      uri:
        url: "{{ truenas_api_url }}/tunable"
        method: POST
        headers:
          Authorization: "Bearer {{ truenas_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          type: "ZFS"
          var: "{{ item.var }}"
          value: "{{ item.value }}"
          enabled: true
          comment: "{{ item.comment | default('ZFS performance tunable managed by Ansible') }}"
        status_code: [200, 201]
        validate_certs: "{{ truenas_validate_certs }}"
      loop: "{{ performance_zfs_tunables }}"
      loop_control:
        label: "{{ item.var }} = {{ item.value }}"
      register: zfs_results

    - name: Display ZFS configuration results
      debug:
        msg:
          - "ZFS tunables configured: {{ zfs_results.results | selectattr('status', 'in', [200, 201]) | list | length }}"
          - "Failed configurations: {{ zfs_results.results | rejectattr('status', 'in', [200, 201]) | list | length }}"

    - name: Fail if any ZFS tunables failed to configure
      fail:
        msg: "Failed to configure ZFS tunable: {{ item.item.var }} = {{ item.item.value }}"
      loop: "{{ zfs_results.results }}"
      when: item.status not in [200, 201]
      loop_control:
        label: "{{ item.item.var }}"

  rescue:
    - name: Handle ZFS configuration errors
      debug:
        msg:
          - "Error configuring ZFS tunables:"
          - "{{ ansible_failed_result.msg | default('Unknown error') }}"

    - name: Re-raise ZFS error
      fail:
        msg: "ZFS tunable configuration failed: {{ ansible_failed_result.msg | default('Unknown error') }}"