---
# Default ZFS pool name
zfs_pool: tank

# TrueNAS API Configuration
truenas_api_url: "https://{{ ansible_host }}/api/v2.0"
truenas_api_key: "{{ vault_truenas_api_key }}"
truenas_validate_certs: true

# Default ZFS properties
default_compression: lz4
default_atime: off
default_xattr: sa

# Main datasets
main_datasets:
  - { name: "{{ zfs_pool }}/apps", recordsize: "128K" }
  - { name: "{{ zfs_pool }}/containers", recordsize: "128K" }
  - { name: "{{ zfs_pool }}/media", recordsize: "1M", compression: "off" }
  - { name: "{{ zfs_pool }}/downloads", recordsize: "128K" }
  - { name: "{{ zfs_pool }}/databases", recordsize: "16K" }
  - { name: "{{ zfs_pool }}/backups", recordsize: "1M" }
  - { name: "{{ zfs_pool }}/logs", recordsize: "128K" }
  - { name: "{{ zfs_pool }}/system", recordsize: "128K" }

# Container runtime datasets
container_datasets:
  - { name: "{{ zfs_pool }}/containers/docker", recordsize: "64K" }
  - { name: "{{ zfs_pool }}/containers/docker/volumes", recordsize: "64K" }
  - { name: "{{ zfs_pool }}/containers/docker/overlay2", recordsize: "64K" }
  - { name: "{{ zfs_pool }}/containers/docker/containers", recordsize: "64K" }
  - { name: "{{ zfs_pool }}/containers/docker/builder", recordsize: "64K" }
  - { name: "{{ zfs_pool }}/containers/lxc", recordsize: "128K" }

# Application datasets by category
app_categories:
  media:
    - plex
    - tautulli
    - overseerr
    - radarr
    - sonarr
    - lidarr
    - readarr
    - prowlarr
    - bazarr
    - whisparr
    - stash
  download:
    - qbittorrent
    - sabnzbd
    - gluetun
    - flaresolverr
  security:
    - authentik
    - traefik
    - wireguard
    - cloudflared
    - crowdsec
    - smallstep
    - wazuh
    - tarpit
    - honeypot
  web:
    - bookstack
    - freshrss
    - homepage
    - homarr
  devops:
    - gitlab
    - harbor
    - awx
  monitoring:
    - prometheus
    - grafana
    - alertmanager
    - librenms
    - uptimekuma
    - gotify
    - netdata
    - scrutiny
    - telegraf
    - graylog
    - nut
    - speedtest
  containers:
    - portainer
    - watchtower
  storage:
    - minio
    - rclone
    - restic
    - velero
  network:
    - pihole
    - technitium
    - chrony
  automation:
    - homeassistant
    - nodered
    - n8n

# Media subdatasets
media_subdatasets:
  - { name: "{{ zfs_pool }}/media/movies", recordsize: "1M", compression: "off" }
  - { name: "{{ zfs_pool }}/media/tv", recordsize: "1M", compression: "off" }
  - { name: "{{ zfs_pool }}/media/music", recordsize: "1M", compression: "off" }
  - { name: "{{ zfs_pool }}/media/books", recordsize: "1M", compression: "off" }
  - { name: "{{ zfs_pool }}/media/audiobooks", recordsize: "1M", compression: "off" }
  - { name: "{{ zfs_pool }}/media/podcasts", recordsize: "1M", compression: "off" }

# Download subdatasets
download_subdatasets:
  - { name: "{{ zfs_pool }}/downloads/incomplete", recordsize: "128K" }
  - { name: "{{ zfs_pool }}/downloads/complete", recordsize: "128K" }
  - { name: "{{ zfs_pool }}/downloads/torrents", recordsize: "128K" }
  - { name: "{{ zfs_pool }}/downloads/usenet", recordsize: "128K" }

# Database datasets with optimized recordsizes
database_datasets:
  - { name: "{{ zfs_pool }}/databases/postgres", recordsize: "16K", owner: postgres, group: database }
  - { name: "{{ zfs_pool }}/databases/mariadb", recordsize: "16K", owner: mariadb, group: database }
  - { name: "{{ zfs_pool }}/databases/redis", recordsize: "8K", owner: redis, group: database }
  - { name: "{{ zfs_pool }}/databases/mongodb", recordsize: "16K", owner: mongodb, group: database }
  - { name: "{{ zfs_pool }}/databases/elasticsearch", recordsize: "16K", owner: elasticsearch, group: database }
  - { name: "{{ zfs_pool }}/databases/influxdb", recordsize: "128K", owner: influxdb, group: database }

# Backup subdatasets
backup_subdatasets:
  - { name: "{{ zfs_pool }}/backups/config", recordsize: "1M" }
  - { name: "{{ zfs_pool }}/backups/database", recordsize: "1M" }
  - { name: "{{ zfs_pool }}/backups/snapshots", recordsize: "1M" }
  - { name: "{{ zfs_pool }}/backups/timemachine", recordsize: "1M" }

# System datasets
system_datasets:
  - { name: "{{ zfs_pool }}/system/truenas", recordsize: "128K" }
  - { name: "{{ zfs_pool }}/system/ca", recordsize: "128K" }

# Special record size adjustments
special_recordsizes:
  - { dataset: "{{ zfs_pool }}/apps/minio", recordsize: "1M" }

# All services for log datasets (61 services total)
all_services:
  - plex
  - tautulli
  - overseerr
  - radarr
  - sonarr
  - lidarr
  - readarr
  - prowlarr
  - bazarr
  - whisparr
  - stash
  - qbittorrent
  - sabnzbd
  - gluetun
  - flaresolverr
  - authentik
  - traefik
  - wireguard
  - cloudflared
  - crowdsec
  - smallstep
  - wazuh
  - tarpit
  - honeypot
  - bookstack
  - freshrss
  - homepage
  - homarr
  - gitlab
  - harbor
  - awx
  - prometheus
  - grafana
  - alertmanager
  - librenms
  - uptimekuma
  - gotify
  - netdata
  - scrutiny
  - telegraf
  - graylog
  - nut
  - speedtest
  - portainer
  - watchtower
  - minio
  - rclone
  - restic
  - velero
  - pihole
  - technitium
  - chrony
  - homeassistant
  - nodered
  - n8n

# Additional system log directories
system_logs:
  - docker
  - system
  - audit