---
collections:
  - name: community.general
    version: ">=6.0.0"
    source: https://galaxy.ansible.com

  - name: ansible.posix
    version: ">=1.4.0"
    source: https://galaxy.ansible.com

roles: []