---
- name: TrueNAS SCALE Infrastructure Setup
  hosts: truenas
  become: true
  gather_facts: true
  vars:
    zfs_pool: "{{ hostvars[inventory_hostname]['zfs_pool'] | default('tank') }}"

  pre_tasks:
    - name: Verify ZFS pool exists via TrueNAS API
      uri:
        url: "{{ truenas_api_url }}/pool/{{ zfs_pool }}"
        method: GET
        headers:
          Authorization: "Bearer {{ truenas_api_key }}"
        status_code: [200]
        validate_certs: "{{ truenas_validate_certs | default(true) }}"
      register: pool_status
      tags: always

    - name: Display setup information
      debug:
        msg:
          - "Starting TrueNAS SCALE setup for host: {{ inventory_hostname }}"
          - "Target ZFS pool: {{ zfs_pool }}"
          - "Total services to configure: 61"
      tags: always

  roles:
    - role: truenas_users
      tags:
        - users
        - setup

    - role: truenas_datasets
      tags:
        - datasets
        - zfs
        - setup

    - role: truenas_snapshots
      tags:
        - snapshots
        - backup
        - setup

  post_tasks:
    - name: Display completion summary
      debug:
        msg:
          - "TrueNAS SCALE infrastructure setup completed successfully!"
          - "Users created: {{ service_users | length }} service users across {{ service_groups | length }} groups"
          - "Datasets created: Main datasets, application datasets for all {{ service_users | length }} services"
          - "Snapshots configured: {{ snapshot_method | title }} snapshot management enabled"
          - ""
          - "Next steps:"
          - "1. Deploy your containerized services using the created users and datasets"
          - "2. Configure application-specific permissions as needed"
          - "3. Monitor snapshot operations and adjust retention policies if required"
          - "4. Review generated reference files in /tmp/ (users_groups_reference.txt, docker_users.env)"
      tags: always

    - name: Generate deployment summary
      template:
        src: deployment_summary.md.j2
        dest: /tmp/truenas_deployment_summary.md
        mode: '0644'
      delegate_to: localhost
      tags: always