---
- name: Test Batch Processing for Performance Tunables
  hosts: localhost
  become: false
  gather_facts: true
  connection: local
  vars:
    truenas_api_key: "{{ lookup('env', 'TRUENAS_API_KEY') }}"

    # Conservative batch processing settings for testing
    tunable_batch_size: 3           # Small batches for testing
    tunable_throttle_delay: 5       # Short delays for testing
    tunable_batch_delay: 15         # Moderate delay between batches

    # Test with just a few tunables
    performance_tunables:
      - name: "vm.swappiness"
        type: "SYSCTL"
        value: "1"
        description: "Minimize swap usage"
        comment: "Test batch 1: VM swappiness"
        enabled: true

      - name: "vm.dirty_ratio"
        type: "SYSCTL"
        value: "10"
        description: "Dirty page ratio"
        comment: "Test batch 1: Dirty ratio"
        enabled: true

      - name: "vm.vfs_cache_pressure"
        type: "SYSCTL"
        value: "50"
        description: "VFS cache pressure"
        comment: "Test batch 1: VFS cache"
        enabled: true

      - name: "net.core.rmem_max"
        type: "SYSCTL"
        value: "134217728"
        description: "Max receive buffer"
        comment: "Test batch 2: Network receive buffer"
        enabled: true

      - name: "net.core.wmem_max"
        type: "SYSCTL"
        value: "134217728"
        description: "Max send buffer"
        comment: "Test batch 2: Network send buffer"
        enabled: true

      - name: "zfs_admin_snapshot"
        type: "ZFS"
        value: "1"
        description: "Admin snapshots"
        comment: "Test batch 2: ZFS admin snapshot"
        enabled: true

  pre_tasks:
    - name: Check TRUENAS_API_KEY environment variable
      fail:
        msg: "TRUENAS_API_KEY environment variable is not set"
      when: truenas_api_key == ""

    - name: Display batch processing test information
      debug:
        msg:
          - "Testing batch processing with 6 tunables"
          - "Batch size: {{ tunable_batch_size }} tunables"
          - "Expected batches: 2 (3 tunables each)"
          - "Throttle delay: {{ tunable_throttle_delay }}s between operations"
          - "Batch delay: {{ tunable_batch_delay }}s between batches"
          - "Estimated time: ~2 minutes"

  roles:
    - role: performance
      tags:
        - performance
        - batch
        - test

  post_tasks:
    - name: Display batch processing test completion
      debug:
        msg:
          - "Batch processing test completed!"
          - "Check /tmp/truenas_performance_report.txt for details"
          - "All tunables should be created without job queue saturation"