---
# Debug SSH Service API Endpoint
# This file helps identify the correct SSH service endpoint in TrueNAS SCALE

- name: Get all available services from TrueNAS API
  uri:
    url: "{{ truenas_api_url }}/service"
    method: GET
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
    validate_certs: "{{ truenas_validate_certs }}"
  register: all_services
  tags:
    - debug
    - ssh
    - api

- name: Display all available services
  debug:
    msg: "Available services: {{ all_services.json | map(attribute='service') | list | sort }}"
  tags:
    - debug
    - ssh

- name: Find SSH-related services
  debug:
    msg: "SSH-related services: {{ all_services.json | selectattr('service', 'match', '.*ssh.*') | map(attribute='service') | list }}"
  tags:
    - debug
    - ssh

- name: Display SSH service details
  debug:
    var: item
  loop: "{{ all_services.json | selectattr('service', 'match', '.*ssh.*') | list }}"
  tags:
    - debug
    - ssh

- name: Try alternative SSH service names
  uri:
    url: "{{ truenas_api_url }}/service/id/{{ item }}"
    method: GET
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
    validate_certs: "{{ truenas_validate_certs }}"
  loop:
    - ssh
    - openssh
    - sshd
  register: ssh_service_attempts
  failed_when: false
  tags:
    - debug
    - ssh
    - api

- name: Display successful SSH service endpoint
  debug:
    msg:
      - "Service ID '{{ item.item }}' returned status: {{ item.status }}"
      - "{% if item.status == 200 %}✅ SUCCESS: Use service ID '{{ item.item }}'{% else %}❌ FAILED{% endif %}"
  loop: "{{ ssh_service_attempts.results }}"
  tags:
    - debug
    - ssh